Repository SWYP-Woory/woory-frontend, pull requests merged in 2024-07, with the labels that each got.

#4 Tailwind Color 세팅
  src/app/layout.tsx
  tailwind.config.ts
Labels: 세팅

#7 fontsize & typography 세팅
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: 세팅

#8 ESLint + Prettier 세팅
  .eslintrc.json
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app/page.tsx
Labels: 세팅

#11 InputText 컴포넌트 스타일링
  .eslintrc.json
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/input/InputText.tsx
Labels: 컴포넌트

#12 스토리북 세팅 및 InputText 스토리북 추가
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/components/input/InputText.stories.tsx
  src/components/input/InputText.tsx
Labels: 세팅

#15 팝업버튼 컴포넌트 추가
  package.json
  pnpm-lock.yaml
  src/components/common/PopUpButton.stories.tsx
  src/components/common/PopUpButton.tsx
  tailwind.config.ts
Labels: 컴포넌트

#19 스토리북을 위한 eslint 수정 및 husky 도입
  .eslintrc.json
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/components/common/PopUpButton.tsx
Labels: 세팅

#16 Icon 컴포넌트 생성
  .eslintrc.json
  .storybook/main.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/next.svg
  public/vercel.svg
  src/assets/icons/arrow/leftArrow.svg
  src/assets/icons/arrow/rightArrow.svg
  src/assets/icons/bottomBar/activeHeart.svg
  src/assets/icons/bottomBar/activeHome.svg
  src/assets/icons/bottomBar/activeMember.svg
  src/assets/icons/bottomBar/activeMypage.svg
  src/assets/icons/bottomBar/heart.svg
  src/assets/icons/bottomBar/home.svg
  src/assets/icons/bottomBar/member.svg
  src/assets/icons/bottomBar/mypage.svg
  src/assets/icons/comment/comment.svg
  src/assets/icons/delete/delete.svg
  src/assets/icons/info/info.svg
  src/assets/icons/kebabMenu/kebabMenu.svg
  src/assets/icons/like/activeLike.svg
  src/assets/icons/like/like.svg
  src/assets/icons/notification/activeNotice.svg
  src/assets/icons/notification/notice.svg
  src/assets/icons/reaction/greyHeart.svg
  src/assets/icons/reaction/heart.svg
  src/assets/icons/reaction/sad.svg
  src/assets/icons/reaction/smile.svg
  src/assets/icons/reaction/surprise.svg
  src/assets/icons/reaction/thumbs.svg
  src/components/icon/Icons.stories.tsx
  src/components/icon/arrow/LeftArrowIcon.tsx
  src/components/icon/arrow/RightArrowIcon.tsx
  src/components/icon/bottomBar/HeartIcon.tsx
  src/components/icon/bottomBar/HomeIcon.tsx
  src/components/icon/bottomBar/MemberIcon.tsx
  src/components/icon/bottomBar/MyPageIcon.tsx
  src/components/icon/comment/CommentIcon.tsx
  src/components/icon/delete/DeleteIcon.tsx
  src/components/icon/info/InfoIcon.tsx
  src/components/icon/kebabMenu/KebabMenuIcon.tsx
  src/components/icon/like/LikeIcon.tsx
  src/components/icon/notification/NoticeIcon.tsx
  src/components/icon/reaction/GreyHeartIcon.tsx
  src/components/icon/reaction/RcHeartIcon.tsx
  src/components/icon/reaction/SadIcon.tsx
  src/components/icon/reaction/SmileIcon.tsx
  src/components/icon/reaction/SurpriseIcon.tsx
  src/components/icon/reaction/ThumbsIcon.tsx
  src/components/input/InputText.stories.tsx
  src/components/input/InputText.tsx
Labels: 컴포넌트

#20 Bar 컴포넌트 생성
  src/app/globals.css
  src/components/common/Header/BasicHeader.tsx
  src/components/common/Header/ControlHeader.tsx
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/NotificationHeader.tsx
  src/components/common/bottomMenuBar/BottomMenuBar.stories.tsx
  src/components/common/bottomMenuBar/BottomMenuBar.tsx
  src/components/icon/Icons.stories.tsx
  src/components/icon/notification/NoticeIcon.tsx
Labels: 컴포넌트

#23 Button 컴포넌트 추가
  src/assets/images/kakao-image.png
  src/components/common/button/KakaoButton.stories.tsx
  src/components/common/button/KakaoButton.tsx
  src/components/common/button/PopUpButton.stories.tsx
  src/components/common/button/PopUpButton.tsx
Labels: 컴포넌트

#27 1번만 사용하는 컴포넌트 추가
  src/assets/icons/addButton/default-add.svg
  src/assets/icons/addButton/pressed-add.svg
  src/assets/icons/checkbox/active-checkbox.svg
  src/assets/icons/checkbox/default-checkbox.svg
  src/assets/icons/checkbox/disabled-checkbox.svg
  src/assets/icons/link/link.svg
  src/components/checkbox/Checkbox.stories.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/common/button/AgreeButton.stories.tsx
  src/components/common/button/AgreeButton.tsx
  src/components/common/header/BasicHeader.tsx
  src/components/common/header/ControlHeader.tsx
  src/components/common/header/Header.stories.tsx
  src/components/common/header/NotificationHeader.tsx
  src/components/icon/Icons.stories.tsx
  src/components/icon/addButton/AddButton.module.css
  src/components/icon/addButton/AddButton.tsx
  src/components/icon/link/LinkIcon.tsx
Labels: 컴포넌트

#32 PopUp & Switch 컴포넌트 생성
  src/components/common/button/PopUpButton.tsx
  src/components/popup/Modal.tsx
  src/components/popup/PopUp.stories.tsx
  src/components/popup/ToastPopUp.tsx
  src/components/switch/ToggleSwitch.stories.tsx
  src/components/switch/ToggleSwitch.tsx
Labels: 컴포넌트

#33 img 컴포넌트 추가
  src/assets/icons/profile/default-small.svg
  src/assets/icons/profile/default.svg
  src/assets/images/img_rectangle_small.png
  src/assets/images/img_square_large.png
  src/assets/images/img_square_middle.png
  src/assets/images/img_square_small.png
  src/components/checkbox/Checkbox.stories.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/icon/Icons.stories.tsx
  src/components/icon/profile/DefaultProfileImage.tsx
  src/components/icon/profile/Profile.tsx
Labels: 컴포넌트

#34 1번만 사용하는 컴포넌트 생성
  src/assets/icons/post/post.svg
  src/components/common/bottomMenuBar/BottomMenuBar.tsx
  src/components/common/button/KakaoButton.stories.tsx
  src/components/common/button/PostButton.stories.tsx
  src/components/common/button/PostButton.tsx
  src/components/upperTabBar/TabButton.tsx
  src/components/upperTabBar/UpperTabBar.stories.tsx
  src/components/upperTabBar/UpperTabBar.tsx
  src/type/index.ts
  tailwind.config.ts
Labels: 컴포넌트

#37 채팅 Input 컴포넌트 생성
  src/assets/icons/send/send.svg
  src/components/input/InputChat.tsx
  src/components/input/InputText.stories.tsx
  src/components/input/InputText.tsx
  src/components/input/Inputs.stories.tsx
Labels: 컴포넌트

#39 바텀 시트 컴포넌트 추가
  src/assets/icons/logo/logo_woory.svg
  src/components/common/bottomSheet/BottomSheet.stories.tsx
  src/components/common/bottomSheet/BottomSheet.tsx
  src/components/common/button/AgreeButton.stories.tsx
  src/components/common/button/BottmSheetButton.stories.tsx
  src/components/common/button/BottomSheetButton.tsx
  src/type/index.ts
Labels: 컴포넌트

#42 기타 컴포넌트 생성
  src/assets/icons/close/imageClose.svg
  src/assets/icons/delete/imageDelete.svg
  src/assets/icons/delete/memberDelete.svg
  src/assets/icons/picture/picture.svg
  src/assets/icons/profile/householder.svg
  src/components/icon/Icons.stories.tsx
  src/components/icon/delete/ImageDeleteIcon.tsx
  src/components/icon/delete/MemberDeleteIcon.tsx
  src/components/icon/profile/Profile.tsx
  src/components/imageUpload/ImageUpload.stories.tsx
  src/components/imageUpload/ImageUpload.tsx
Labels: 컴포넌트

#44 chip 컴포넌트 이름 변경 및 수정사항 적용
  src/components/chip/AddReactionChip.tsx
  src/components/chip/Chips.stories.tsx
  src/components/chip/HeartChip.tsx
  src/components/chip/ReactionChip.tsx
  src/type/index.ts
Labels: 컴포넌트, fix

#47 마음함, 알림함 컴포넌트 추가
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/assets/icons/bottomBar/activeHeart.svg
  src/assets/icons/logo/logo_woory_post.svg
  src/components/icon/bottomBar/HeartIcon.tsx
  src/components/notification/NotificationBox.stories.tsx
  src/components/notification/NotificationBox.tsx
  src/components/post/DefaultPostImage.tsx
  src/components/post/favorite/FavoritePost.stories.tsx
  src/components/post/favorite/FavoritePost.tsx
  src/type/index.ts
  src/utils/getTime.ts
Labels: 컴포넌트

#48 캘린더뷰 컴포넌트 생성
  pnpm-lock.yaml
  src/app/globals.css
  src/assets/icons/calendar/noImageDay.svg
  src/components/calender/Calender.tsx
  src/components/calender/CalenderController.tsx
  src/components/calender/CalenderView.stories.tsx
  src/components/calender/CalenderView.tsx
  src/components/calender/Day.tsx
  src/type/index.ts
Labels: 컴포넌트

#56 로그인 페이지 레이아웃 구현
  .gitignore
  src/app/(beforeLogin)/_components/SocialButton.stories.tsx
  src/app/(beforeLogin)/_components/SocialLogin.tsx
  src/app/(beforeLogin)/_components/SocialLoginButton.tsx
  src/app/(beforeLogin)/_components/Terms.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_components/checkbox/Checkbox.tsx
  src/app/_components/common/button/KakaoButton.stories.tsx
  src/app/_components/common/button/KakaoButton.tsx
  src/app/globals.css
  src/app/page.tsx
  src/assets/images/naver-image.png
Labels: 페이지

#62 global 레이아웃, box shadow 스타일 세팅 추가
  src/app/(beforeLogin)/layout.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: 스타일

#63 배포를 위한 PR 테스트
  src/app/(beforeLogin)/_components/modal/AgreementModal.tsx
Labels: 스타일

#64 타입에러로 빌드를 실패하여 타입 수정
  src/app/_components/notification/NotificationBox.tsx
Labels: fix

#58 게시글 페이지 레이아웃
  next.config.mjs
  src/app/(afterLogin)/posts/[postId]/layout.tsx
  src/app/(afterLogin)/posts/[postId]/page.tsx
  src/app/(afterLogin)/posts/_components/DailyPostView.stories.tsx
  src/app/(afterLogin)/posts/_components/DailyPostView.tsx
  src/app/(afterLogin)/posts/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/_components/input/InputComment.tsx
  src/app/(afterLogin)/posts/_components/reaction/ReactionMenu.stories.tsx
  src/app/(afterLogin)/posts/_components/reaction/ReactionMenu.tsx
  src/app/(afterLogin)/posts/_components/reaction/ReactionSection.tsx
  src/app/(afterLogin)/posts/_components/reaction/chip/AddReactionChip.tsx
  src/app/(afterLogin)/posts/_components/reaction/chip/Chips.stories.tsx
  src/app/(afterLogin)/posts/_components/reaction/chip/ReactionChip.tsx
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/_components/common/button/EditDeleteButton.tsx
  src/app/_components/common/button/PopUpButton.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/header/BasicHeader.tsx
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/icon/kebabMenu/KebabMenuIcon.tsx
  src/app/_components/input/InputChat.tsx
  src/app/_components/popup/Modal.tsx
  src/app/_constants/modal.tsx
  src/app/globals.css
  src/app/posts/_components/comment/CommentView.tsx
  src/type/index.ts
Labels: 페이지

#60 게시글 작성 페이지 레이아웃
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/input/InputComment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionMenu.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionMenu.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionSection.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/chip/AddReactionChip.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/chip/Chips.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/chip/ReactionChip.tsx
  src/app/(afterLogin)/posts/[postId]/page.tsx
  src/app/(afterLogin)/posts/_components/InputDailyContent.tsx
  src/app/(afterLogin)/posts/layout.tsx
  src/app/(afterLogin)/posts/page.tsx
  src/app/_components/common/header/BasicHeader.tsx
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/imageUpload/ImageUpload.tsx
  src/app/_components/input/InputText.tsx
  src/app/_store/inputStore.ts
Labels: 페이지

#67 서비스 이용약관 및 개인정보 처리방침 모달 스타일 수정 / 타입 에러 제거
  package.json
  src/app/(beforeLogin)/_components/AgreementDescription.tsx
  src/app/(beforeLogin)/_components/Main.tsx
  src/app/(beforeLogin)/_components/modal/AgreementModal.tsx
  src/app/(beforeLogin)/layout.tsx
  src/app/_components/common/bottomSheet/BottomSheet.tsx
  src/app/_components/common/button/EditDeleteButton.stories.tsx
  src/app/_components/common/button/PopUpButton.stories.tsx
  src/app/_components/daily/DailyThread.tsx
  src/app/_components/icon/Icons.stories.tsx
  src/app/_components/popup/PopUp.stories.tsx
  tailwind.config.ts
Labels: fix, 페이지

#72 멤버 페이지 레이아웃
  src/app/(afterLogin)/members/_components/MemberAdd.tsx
  src/app/(afterLogin)/members/_components/MemberMain.tsx
  src/app/(afterLogin)/members/_components/MemberProfile.tsx
  src/app/(afterLogin)/members/_components/MyProfile.tsx
  src/app/(afterLogin)/members/page.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/profile/Profile.tsx
  src/app/_components/icon/delete/MemberDeleteIcon.tsx
  src/app/_components/popup/Modal.tsx
  src/app/_components/popup/ToastPopUp.tsx
  src/app/_constants/modal.tsx
  src/type/index.ts
Labels: 페이지

#74 마이 페이지 레이아웃
  src/app/(afterLogin)/myPage/_components/MyTitle.tsx
  src/app/(afterLogin)/myPage/_components/OptionTitle.tsx
  src/app/(afterLogin)/myPage/_components/account/AccountSetting.tsx
  src/app/(afterLogin)/myPage/_components/addHome/AddHome.tsx
  src/app/(afterLogin)/myPage/_components/family/FamilyItem.tsx
  src/app/(afterLogin)/myPage/_components/family/FamilySetting.tsx
  src/app/(afterLogin)/myPage/_components/notification/NotificationItem.tsx
  src/app/(afterLogin)/myPage/_components/notification/NotificationSetting.tsx
  src/app/(afterLogin)/myPage/_components/service/ServiceInfo.tsx
  src/app/(afterLogin)/myPage/page.tsx
  src/app/(afterLogin)/mypage/_components/MyTitle.tsx
  src/app/(afterLogin)/mypage/_components/OptionTitle.tsx
  src/app/(afterLogin)/mypage/_components/account/AccountSetting.tsx
  src/app/(afterLogin)/mypage/_components/addHome/AddHome.tsx
  src/app/(afterLogin)/mypage/_components/family/FamilyItem.tsx
  src/app/(afterLogin)/mypage/_components/family/FamilySetting.tsx
  src/app/(afterLogin)/mypage/_components/notification/NotificationItem.tsx
  src/app/(afterLogin)/mypage/_components/notification/NotificationSetting.tsx
  src/app/(afterLogin)/mypage/_components/service/ServiceInfo.tsx
  src/app/(afterLogin)/mypage/page.tsx
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/_components/common/profile/DefaultProfileImage.tsx
  src/app/_components/common/profile/Profile.tsx
  src/app/_components/icon/Icons.stories.tsx
  src/app/_components/switch/ToggleSwitch.stories.tsx
  src/app/_components/switch/ToggleSwitch.tsx
  src/app/globals.css
  src/assets/icons/addHome/addHome.svg
  src/assets/icons/family/family.svg
  src/assets/icons/info/serviceInfo.svg
  src/assets/icons/profile/default-xlarge.svg
  src/assets/icons/setting/setting.svg
  src/type/index.ts
  tsconfig.json
Labels: 페이지

#76 홈 데일리 페이지 작성
  src/app/(afterLogin)/(main)/daily/[day]/_components/daily/Daily.stories.tsx
  src/app/(afterLogin)/(main)/daily/[day]/_components/daily/DailyNoThread.tsx
  src/app/(afterLogin)/(main)/daily/[day]/_components/daily/DailyThread.tsx
  src/app/(afterLogin)/(main)/daily/[day]/_components/daily/DailyView.tsx
  src/app/(afterLogin)/(main)/daily/[day]/page.tsx
  src/app/(afterLogin)/(main)/favorites/_components/DefaultPostImage.tsx
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.stories.tsx
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.tsx
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePostView.tsx
  src/app/(afterLogin)/(main)/favorites/page.tsx
  src/app/(afterLogin)/(main)/layout.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberAdd.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberProfile.tsx
  src/app/(afterLogin)/(main)/members/_components/MyProfile.tsx
  src/app/(afterLogin)/(main)/members/page.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyTitle.tsx
  src/app/(afterLogin)/(main)/mypage/_components/OptionTitle.tsx
  src/app/(afterLogin)/(main)/mypage/_components/account/AccountSetting.tsx
  src/app/(afterLogin)/(main)/mypage/_components/addHome/AddHome.tsx
  src/app/(afterLogin)/(main)/mypage/_components/family/FamilyItem.tsx
  src/app/(afterLogin)/(main)/mypage/_components/family/FamilySetting.tsx
  src/app/(afterLogin)/(main)/mypage/_components/notification/NotificationItem.tsx
  src/app/(afterLogin)/(main)/mypage/_components/notification/NotificationSetting.tsx
  src/app/(afterLogin)/(main)/mypage/_components/service/ServiceInfo.tsx
  src/app/(afterLogin)/(main)/mypage/page.tsx
  src/app/(afterLogin)/members/page.tsx
  src/app/(afterLogin)/mypage/page.tsx
  src/app/_components/calender/CalenderView.tsx
  src/app/_components/common/button/PostButton.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/header/Header.stories.tsx
  src/app/_components/common/header/NotificationHeader.tsx
  src/app/_components/common/profile/DefaultProfileImage.tsx
  src/app/_components/common/profile/Profile.tsx
  src/app/_components/daily/Daily.stories.tsx
  src/app/_components/daily/DailyView.tsx
  src/app/_hooks/useDateControl.ts
Labels: 페이지

#80 로그인 페이지 레이아웃 및 NotificationHeader 함수 수정
  src/app/(beforeLogin)/_components/Main.tsx
  src/app/(beforeLogin)/_components/Terms.tsx
  src/app/_components/common/header/NotificationHeader.tsx
Labels: fix, 페이지, 스타일

#81 홈 캘린더 페이지 작업
  src/app/(afterLogin)/(main)/home/calendar/[month]/_components/calendar/Calendar.tsx
  src/app/(afterLogin)/(main)/home/calendar/[month]/_components/calendar/CalendarView.stories.tsx
  src/app/(afterLogin)/(main)/home/calendar/[month]/_components/calendar/CalendarView.tsx
  src/app/(afterLogin)/(main)/home/calendar/[month]/_components/calendar/Day.tsx
  src/app/(afterLogin)/(main)/home/calendar/[month]/page.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/Daily.stories.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyNoThread.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyThread.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyView.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/page.tsx
  src/app/(beforeLogin)/_components/Main.tsx
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/_components/common/header/NotificationHeader.tsx
  src/app/_components/upperTabBar/TabButton.tsx
  src/app/_components/upperTabBar/UpperTabBar.tsx
  src/app/_store/homeTabStore.ts
  src/type/index.ts
Labels: 페이지

#85 디자인 수정사항 적용
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePostView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/_components/imageUpload/ImageUpload.tsx
Labels: fix, 페이지, 스타일

#86 알림페이지 추가
  src/app/(afterLogin)/notification/_components/notification/Notification.tsx
  src/app/(afterLogin)/notification/_components/notification/NotificationBox.stories.tsx
  src/app/(afterLogin)/notification/_components/notification/NotificationBox.tsx
  src/app/(afterLogin)/notification/_components/notification/NotificationList.tsx
  src/app/(afterLogin)/notification/page.tsx
  src/app/_components/notification/NotificationBox.tsx
  src/type/index.ts
  src/utils/getTime.ts
  tailwind.config.ts
Labels: 페이지

#94 Github Actios CI 연결
  .github/pull-request-template.md
  .github/workflows/front-ci.yml
Labels: 세팅

#95 Github Actions CI 연결
  .github/workflows/front-ci.yml
Labels: 세팅

#92 OAuth Kakao, Naver 링크 연결
  src/app/(beforeLogin)/_components/SocialLoginButton.tsx
  src/app/_constants/domain.ts
  src/app/_constants/modal.ts
Labels: 기능

#96 가족 상태 수정 페이지, 프로필 수정 페이지 레이아웃
  src/app/(afterLogin)/(main)/mypage/_components/notification/NotificationItem.tsx
  src/app/(afterLogin)/(main)/mypage/_components/switch/ToggleSwitch.stories.tsx
  src/app/(afterLogin)/(main)/mypage/_components/switch/ToggleSwitch.tsx
  src/app/(afterLogin)/(profile)/_components/NameInput.tsx
  src/app/(afterLogin)/(profile)/_components/ProfileMain.tsx
  src/app/(afterLogin)/(profile)/family-edit/@modal/(.)family-delete/page.tsx
  src/app/(afterLogin)/(profile)/family-edit/@modal/default.tsx
  src/app/(afterLogin)/(profile)/family-edit/family-delete/page.tsx
  src/app/(afterLogin)/(profile)/family-edit/layout.tsx
  src/app/(afterLogin)/(profile)/family-edit/page.tsx
  src/app/(afterLogin)/(profile)/family/page.tsx
  src/app/(afterLogin)/(profile)/profile/page.tsx
  src/app/(beforeLogin)/family/_components/FamilyImageUpload.tsx
  src/app/(beforeLogin)/family/_components/FamilyNameInput.tsx
  src/app/(beforeLogin)/family/page.tsx
  src/app/_components/common/header/BasicHeader.tsx
  src/app/_components/common/header/Header.stories.tsx
  src/app/_components/common/profile/BigProfile.tsx
  src/app/_components/common/profile/FamilyProfile.tsx
  src/app/_components/common/profile/Profile.stories.tsx
  src/app/_components/common/profile/ProfileImageUpload.tsx
  src/app/_constants/modal.ts
  src/app/_hooks/useImageUpload.ts
  src/app/_hooks/useToast.ts
  src/app/_store/inputStore.ts
  src/assets/images/default_profile.png
  src/type/index.ts
  src/utils/getInputHandler.ts
Labels: 페이지

#99 사진 용량 초과 시 Toast 팝업
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/PostButton.stories.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/PostButton.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/page.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyTitle.tsx
  src/app/(afterLogin)/(main)/mypage/_components/family/FamilySetting.tsx
  src/app/(afterLogin)/(profile)/_components/ProfileMain.tsx
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/(afterLogin)/posts/page.tsx
  src/app/_components/common/bottomSheet/FamilySelectButton.tsx
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/common/header/NotificationHeader.tsx
  src/app/_components/common/popup/ToastPopUp.tsx
  src/app/_components/common/profile/DefaultProfileImage.tsx
  src/app/_components/common/profile/Profile.tsx
  src/app/_hooks/useImageUpload.ts
  src/assets/icons/profile/family_profile.svg
  src/type/index.ts
Labels: 기능

#103 가족 선택 페이지 개선 - 뒷배경이 빈화면이 아닌 로그인 페이지가 보이도록
  src/app/(afterLogin)/family-select/page.tsx
Labels: 페이지

#104 홈 화면 추가하기 팝업 및 토스트 추가
  package.json
  pnpm-lock.yaml
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyMain.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/page.tsx
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
  src/app/_store/cookie/cookies.ts
Labels: 기능

#106 이미지 원본을 볼 수 있는 모달
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/[postId]/image-modal/_components/ImageModalMain.tsx
  src/app/(afterLogin)/posts/[postId]/image-modal/page.tsx
  src/app/(afterLogin)/posts/[postId]/page.tsx
  src/app/_components/common/daily/DailyPostImage.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/type/index.ts
Labels: fix, 페이지

#108 404 페이지 추가
  src/app/_components/common/button/PopUpButton.tsx
  src/app/not-found.tsx
  src/assets/icons/logo/logo_square.svg
Labels: 페이지

#109 feat: 이미지최적화 및 UpperTabBar 버그 수정
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.tsx
  src/app/(afterLogin)/(main)/favorites/page.tsx
  src/app/(afterLogin)/(main)/home/calendar/[month]/_components/calendar/Day.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyView.tsx
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/_components/common/daily/DailyPostImage.tsx
  src/app/_components/upperTabBar/UpperTabBar.tsx
Labels: fix, 성능개선

#110 fetch 라이브러리 세팅
  .eslintrc.json
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyMain.tsx
  src/app/_api/api.ts
Labels: 세팅

#111 홈 화면 추가하기 기능 추가
  .eslintrc.json
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/icon512_maskable.png
  public/icon512_rounded.png
  public/sw.js
  public/workbox-e9849328.js
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
  src/app/manifest.ts
Labels: 기능

#113 쿠키 수정하여 홈화면 추가하기 바텀시트 한번만 뜨도록 수정
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyMain.tsx
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
Labels: fix

#115 토스트 버그(다른페이지로 가면 해당 페이지문구로 변하는 버그) 수정
  package.json
  pnpm-lock.yaml
  src/app/(afterLogin)/(main)/home/daily/[day]/_components/daily/DailyMain.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyPageMain.tsx
  src/app/(afterLogin)/(profile)/_components/ProfileMain.tsx
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
  src/app/_components/common/popup/ToastPopUp.tsx
  src/app/_hooks/useImageUpload.ts
  src/app/_hooks/useToast.ts
  src/app/_store/toastStore.ts
  src/app/layout.tsx
  src/type/index.ts
  src/utils/Toast.tsx
Labels: fix

#116 Fix/#114
  .eslintrc.json
  next.config.mjs
  public/sw.js
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
  src/app/_components/common/daily/DailyPostImage.tsx
  tsconfig.json
Labels: fix

#118 쿠키를 확인하기 위한 테스트
  next.config.mjs
  public/sw.js
  public/workbox-e9849328.js
  src/app/(afterLogin)/oauth/callback/[provider]/page.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_api/api.ts
  src/app/_constants/domain.ts
  src/app/_store/cookie/session.ts
  src/middleware.ts
Labels: fix

#123 Github Actions 환경 변수 추가
  .github/workflows/front-ci.yml
Labels: 세팅, fix

#120 header에 토큰 추가
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app/(afterLogin)/(main)/mypage/_components/account/AccountSetting.tsx
  src/app/(afterLogin)/(main)/mypage/account-deletion/_components/AccountDeletionContent.tsx
  src/app/(afterLogin)/(profile)/profile/page.tsx
  src/app/_api/api.ts
  src/app/_api/apiRoutes.ts
  src/app/_components/common/header/BasicHeader.tsx
  src/app/_hooks/useImageUpload.ts
  src/app/_store/imageUploadStore.ts
  src/type/index.ts
Labels: 기능

#125 daily,calender 동적 라우팅 추가 & 가족 선택 페이지 api 연동
  next.config.mjs
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/Calendar.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/CalendarView.stories.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/CalendarView.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/Day.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/page.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/Daily.stories.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/DailyMain.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/DailyNoThread.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/DailyThread.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/DailyView.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/PostButton.stories.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/PostButton.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/page.tsx
  src/app/(afterLogin)/(main)/home/daily/[day]/page.tsx
  src/app/(afterLogin)/oauth/callback/[provider]/page.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/_components/common/bottomSheet/AddFamilySelectButton.tsx
  src/app/_components/common/bottomSheet/BottomSheet.stories.tsx
  src/app/_components/common/bottomSheet/BottomSheet.tsx
  src/app/_components/common/bottomSheet/FamilyBottomSheet.stories.tsx
  src/app/_components/common/bottomSheet/FamilySelect.tsx
  src/app/_components/common/bottomSheet/FamilySelectButton.tsx
  src/app/_components/common/bottomSheet/FamilySelector.tsx
  src/app/_components/upperTabBar/UpperTabBar.tsx
  src/type/index.ts
Labels: fix, 기능

#128 OAuath 로그인 후 가족 선택 페이지 라우팅 오류 & 쿠기에 groupId 확인하여 redirect 작업
  src/app/(afterLogin)/oauth/callback/[provider]/page.tsx
  src/app/(beforeLogin)/@modal/(.)family-select/page.tsx
  src/app/(beforeLogin)/page.tsx
Labels: fix

#132 가족 삭제 API 연결 및 가족 생성시 쿠키 생성 기능 추가
  src/app/(afterLogin)/(profile)/family-edit/@modal/(.)family-delete/page.tsx
  src/app/(afterLogin)/(profile)/family-edit/_components/FamilyDelete.tsx
  src/app/(afterLogin)/(profile)/family-edit/family-delete/page.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/bottomSheet/FamilySelectButton.tsx
  src/app/_components/common/header/BasicHeader.tsx
Labels: fix, 기능

#137 멤버 API 연결
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberProfile.tsx
  src/app/(afterLogin)/(main)/members/_components/MyProfile.tsx
  src/app/(afterLogin)/(profile)/_components/ProfileEditMain.tsx
  src/app/(afterLogin)/(profile)/family-edit/_components/FamilyDelete.tsx
  src/app/_api/apiRoutes.ts
  src/type/index.ts
Labels: 기능

#138 마이 페이지 API 연결 & 알림 관련 UI 숨김
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyPageMain.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/header/NotificationHeader.tsx
  src/app/_components/common/loading/Loading.tsx
  src/app/_components/common/profile/Profile.tsx
  src/type/index.ts
Labels: 스타일, 기능

#140 프로필 수정 API & 이미지, input 상태 데이터 reset 처리
  next.config.mjs
  src/app/(afterLogin)/(main)/mypage/_components/MyPageMain.tsx
  src/app/(afterLogin)/(main)/mypage/_components/family/FamilySetting.tsx
  src/app/(afterLogin)/(profile)/family-edit/_components/FamilyDelete.tsx
  src/app/(afterLogin)/(profile)/family-edit/_components/FamilyProfileEditMain.tsx
  src/app/(afterLogin)/(profile)/family-edit/page.tsx
  src/app/(afterLogin)/(profile)/profile/components/UserProfileEditMain.tsx
  src/app/(afterLogin)/(profile)/profile/page.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/header/BasicHeader.tsx
  src/app/_store/imageUploadStore.ts
  src/app/_store/inputStore.ts
  src/type/index.ts
Labels: fix, 기능

#145 쿠키세팅 path 추가하여 어디든 접근가능하도록 변경
  src/app/_components/common/bottomSheet/FamilySelectButton.tsx
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
  src/app/_components/common/header/BasicHeader.tsx
Labels: fix

#143 게시글 작성 페이지 API 연결
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/(afterLogin)/posts/_components/imageUpload/ImageUpload.tsx
  src/app/(afterLogin)/posts/page.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/common/header/Header.stories.tsx
  src/type/index.ts
Labels: 기능

#147 홈 캘린더 API 연결
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/Calendar.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/CalendarView.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/Day.tsx
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/page.tsx
  src/app/_api/apiRoutes.ts
  src/type/index.ts
Labels: 기능

#149 홈 데일리뷰 API 연결
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/_components/daily/DailyView.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/daily/DailyPostImage.tsx
  src/type/index.ts
Labels: 기능

#150 Next.js 로딩 처리
  src/app/(afterLogin)/(main)/home/[groupId]/calendar/[month]/_components/calendar/CalendarView.tsx
  src/app/(afterLogin)/(main)/loading.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyPageMain.tsx
  src/app/(afterLogin)/(main)/mypage/_components/family/FamilySetting.tsx
  src/app/(afterLogin)/(profile)/family-edit/_components/FamilyProfileEditMain.tsx
  src/app/(afterLogin)/(profile)/layout.tsx
  src/app/(afterLogin)/(profile)/loading.tsx
  src/app/(afterLogin)/(profile)/profile/components/UserProfileEditMain.tsx
  src/app/(afterLogin)/loading.tsx
  src/app/(afterLogin)/oauth/callback/[provider]/page.tsx
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/_components/common/bottomSheet/FamilySelect.tsx
  src/type/index.ts
Labels: 페이지, 기능

#152 다이나믹 라우팅 제거
  src/app/(afterLogin)/(main)/home/[groupId]/daily/[day]/page.tsx
  src/app/(afterLogin)/(main)/home/calendar/_components/Calendar.tsx
  src/app/(afterLogin)/(main)/home/calendar/_components/CalendarView.stories.tsx
  src/app/(afterLogin)/(main)/home/calendar/_components/CalendarView.tsx
  src/app/(afterLogin)/(main)/home/calendar/_components/Day.tsx
  src/app/(afterLogin)/(main)/home/calendar/page.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/Daily.stories.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyMain.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyNoThread.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyThread.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/PostButton.stories.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/PostButton.tsx
  src/app/(afterLogin)/(main)/home/daily/page.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/_components/common/bottomSheet/FamilySelectButton.tsx
  src/app/_components/common/upperTabBar/TabButton.tsx
  src/app/_components/common/upperTabBar/UpperTabBar.stories.tsx
  src/app/_components/common/upperTabBar/UpperTabBar.tsx
Labels: fix

#154 캘린더 날짜 이동 버그 수정
  src/app/(afterLogin)/(main)/home/calendar/_components/Day.tsx
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/_components/common/header/BasicHeader.tsx
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/common/header/Header.stories.tsx
Labels: fix

#156 로그아웃, 회원탈퇴 버그 해결 및 구현
  src/app/(afterLogin)/(main)/mypage/_components/account/AccountSetting.tsx
  src/app/(afterLogin)/(main)/mypage/account-deletion/_components/AccountDeletionContent.tsx
  src/app/(beforeLogin)/_components/RedirectHandler.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_store/cookie/cookies.ts
Labels: fix, 기능

#158 이전 날짜, 다음 날짜 화살표 조건부 표현 기능 구현
  src/app/(afterLogin)/(main)/home/calendar/_components/CalendarView.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/_components/common/dateController/DateController.tsx
  src/app/_components/icon/arrow/LeftArrowIcon.tsx
  src/app/_components/icon/arrow/RightArrowIcon.tsx
  src/type/index.ts
Labels: 기능

#160 캘린더에서 날짜 클릭 하여 이동했을 때 데일리 뷰에서 fetch 처리
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/_hooks/useDateControl.ts
Labels: fix, 기능

#161 오늘 날짜 이전이나 이후에 POST(글쓰기) 못하게 막기 - 오늘자로 작성했다면 Toast 팝업띄우기
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/PostButton.tsx
  src/app/_components/common/popup/ToastPopUp.tsx
  src/app/_store/homeTabStore.ts
  src/app/_store/isPostStore.ts
  src/type/index.ts
Labels: 기능

#164 마음함 기능 추가
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.stories.tsx
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.tsx
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePostView.tsx
  src/app/(afterLogin)/(main)/favorites/page.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.tsx
  src/app/(afterLogin)/posts/[postId]/page.tsx
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/_api/api.ts
  src/app/_components/common/daily/DailyPostImage.tsx
  src/app/_components/common/daily/DailyTopic.tsx
  src/app/_components/icon/Icons.stories.tsx
  src/app/_components/icon/like/LikeIcon.tsx
  src/app/_store/LikeStore.ts
  src/app/_store/localstorage/LocalStorage.tsx
  src/app/_store/topicStore.ts
  src/type/index.ts
Labels: 기능

#167 게시글 조회, 수정, 삭제 API 연결
  next.config.mjs
  src/app/(afterLogin)/(main)/home/daily/_components/DailyThread.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/(main)/mypage/_components/account/AccountSetting.tsx
  src/app/(afterLogin)/(main)/mypage/account-deletion/_components/AccountDeletionContent.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.tsx
  src/app/(afterLogin)/posts/[postId]/page.tsx
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/(afterLogin)/posts/_components/imageUpload/ImageUpload.tsx
  src/app/(beforeLogin)/page.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/common/header/Header.stories.tsx
  src/app/_hooks/useImageUpload.ts
  src/app/_store/isImageDeleted.ts
  src/app/_store/isPostDeleted.ts
  src/type/index.ts
Labels: 기능

#170 favicon 적용
  src/app/favicon.ico
  src/app/layout.tsx
Labels: 기능

#172 Meta data 추가
  public/opengraph-image.png
  src/app/layout.tsx
Labels: 세팅, 기능

#174 마음 기능 적용
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.tsx
  src/app/(afterLogin)/(main)/home/calendar/_components/Calendar.tsx
Labels: 기능

#176 리액션 조회, 생성, 삭제 API 연결
  package.json
  pnpm-lock.yaml
  src/app/(afterLogin)/(main)/home/daily/_components/DailyMain.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionMenu.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionMenu.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionSection.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/chip/Chips.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/chip/ReactionChip.tsx
  src/app/_api/apiRoutes.ts
  src/type/index.ts
Labels: 기능

#177 초대받지 않은 가족에 입장한 경우 404에러 처리
  src/app/(afterLogin)/(main)/home/calendar/_components/CalendarView.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
Labels: 기능

#179 홈 화면 추가 옵션에 따른 쿠키 설정
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
Labels: 기능

#181 댓글 조회, 생성, 수정 API 연결
  .eslintrc.json
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentMain.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/input/InputComment.tsx
  src/app/(afterLogin)/posts/[postId]/page.tsx
  src/app/(afterLogin)/posts/_components/imageUpload/ImageUpload.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/input/InputChat.tsx
  src/app/_components/input/Inputs.stories.tsx
  src/app/_hooks/useImageUpload.ts
  src/app/_store/commentListStore.ts
  src/app/_store/commentStore.ts
  src/app/_store/inputCommentStore.ts
  src/app/_store/isImageDeletedStore.ts
  src/app/_store/isPostDeletedStore.ts
  src/app/_store/likeStore.ts
  src/app/_store/replyCommentStore.ts
  src/type/index.ts
Labels: 기능

#182 답글달기 style 적용
  src/app/(afterLogin)/posts/[postId]/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentMain.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/input/InputComment.tsx
  src/app/_components/input/InputChat.tsx
  src/app/_components/input/Inputs.stories.tsx
Labels: 스타일, 기능

#183 댓글 삭제 기능 추가
  src/app/(afterLogin)/posts/[postId]/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentMain.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/daily/DailyUserTitle.tsx
Labels: 기능

#184 자잘한 버그 수정
  src/app/(afterLogin)/posts/[postId]/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/input/InputComment.tsx
  src/app/_components/common/modal/AgreementModal.tsx
Labels: fix, 스타일

#187 약관 동의 화면 맨 위 글자 짤림 수정
  src/app/_components/common/modal/AgreementModal.tsx
Labels: fix

#189 targetType 변경으로 post 수정하기 기능 수정
  src/app/_components/common/daily/DailyUserTitle.tsx
Labels: fix

#192 바텀 메뉴바 스타일 수정
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/globals.css
Labels: fix, 스타일

#193 404 페이지 홈 가기 수정
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/(main)/members/_components/MemberMain.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyPageMain.tsx
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.tsx
Labels: fix

#196 게시글 페이지 UI 오류 수정
  src/app/(afterLogin)/posts/[postId]/_components/DailyPostView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/input/InputComment.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_store/kebabStore.ts
Labels: fix, 스타일, 기능

#197 초대하기로 홈 데일리 들어왔을 때 가족 가입 실패했다면 가족 선택페이지로 이동 및 토스트 팝업
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/family-select/_components/FamilySelectMain.tsx
  src/app/(afterLogin)/family-select/page.tsx
  src/app/_components/common/popup/ToastPopUp.tsx
  src/app/_store/toastStore.ts
  src/type/index.ts
  src/utils/Toast.tsx
Labels: fix, 기능

#199 홈 추가 BottomSheet 제거
  next.config.mjs
  src/app/(afterLogin)/(main)/home/daily/_components/DailyMain.tsx
Labels: fix

#202 가족,프로필 확장자명 지정
  src/app/_components/common/profile/ProfileImageUpload.tsx
Labels: fix

#204 답글달기 오류 수정
  src/app/(afterLogin)/posts/[postId]/_components/comment/Comment.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentMain.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/input/InputComment.tsx
  src/app/_components/input/InputChat.tsx
  src/app/_components/input/Inputs.stories.tsx
  src/app/_store/replyCommentStore.ts
Labels: fix

#205 게시글 케밥 아이콘 수정/삭제 버튼 오류 수정
  src/app/(afterLogin)/(main)/home/daily/_components/DailyThread.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/(afterLogin)/posts/[postId]/_components/comment/CommentView.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_store/kebabStore.ts
  src/type/index.ts
Labels: fix

#206 페이지 이동시 케밥 메뉴 사라지게 수정
  src/app/(afterLogin)/(main)/home/daily/_components/DailyMain.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
Labels: fix

#208 서비스 워커 등록 테스트
  src/ServiceWorkerRegistrar.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyMain.tsx
  src/app/layout.tsx
Labels: 기능

#211 홈 추가, pwa 삭제
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/icon512_maskable.png
  public/icon512_rounded.png
  public/opengraph-image.png
  src/ServiceWorkerRegistrar.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyMain.tsx
  src/app/(afterLogin)/(main)/mypage/account-deletion/_components/AccountDeletionContent.tsx
  src/app/_components/common/bottomSheet/BottomSheet.stories.tsx
  src/app/_components/common/bottomSheet/BottomSheet.tsx
  src/app/_components/common/bottomSheet/HomeShortcut.tsx
  src/app/layout.tsx
  src/app/manifest.ts
  src/type/index.ts
Labels: fix
