Repository SWYP-Woory/woory-frontend, pull requests merged in 2024-08, with the labels that each got.

#213 바텀 시트 애니메이션 추가
  src/app/(afterLogin)/(main)/mypage/@modal/(.)family-select/page.tsx
  src/app/(afterLogin)/(main)/mypage/@modal/(.)service-inquiry/page.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyPageMain.tsx
  src/app/(afterLogin)/(main)/mypage/family-select/page.tsx
  src/app/(afterLogin)/(main)/mypage/service-inquiry/page.tsx
  src/app/(afterLogin)/family-select/page.tsx
  src/app/_components/common/bottomSheet/BottomSheet.tsx
  src/app/_components/common/bottomSheet/ServiceInquiry.tsx
  src/app/_components/common/modal/AgreementModal.tsx
  src/app/_components/common/modal/ModalBackground.tsx
  src/app/_hooks/useModal.ts
  src/app/globals.css
Labels: 컴포넌트, 스타일

#215 토스트 팝업 애니메이션
  src/app/_components/common/popup/PopUp.stories.tsx
  src/app/_components/common/popup/ToastPopUp.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/utils/Toast.tsx
Labels: 컴포넌트, 스타일

#217 리액션 메뉴바 애니메이션
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionMenu.stories.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionMenu.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionSection.tsx
  src/app/_components/common/modal/ModalBackground.tsx
  src/app/globals.css
Labels: 컴포넌트, 스타일

#221 Notification Header 우리 문구 대신 가족 이름 추가
  src/app/_api/apiRoutes.ts
  src/app/_components/common/header/NotificationHeader.tsx
Labels: 기능

#223 토스트 팝업 디자인 수정 & 서비스 기능 소개 모듈 추가
  src/app/(afterLogin)/(main)/mypage/_components/service/ServiceInfo.tsx
  src/app/_components/common/popup/PopUp.stories.tsx
  src/app/_components/common/popup/ToastPopUp.tsx
Labels: fix

#225 가족 선택 바텀 시트 hover, pressed 디자인
  src/app/_components/common/bottomSheet/AddFamilySelectButton.tsx
  src/app/_components/common/bottomSheet/FamilyBottomSheet.stories.tsx
  src/app/_components/common/bottomSheet/FamilySelectButton.tsx
  src/app/_components/common/bottomSheet/FamilySelector.tsx
  src/assets/icons/profile/family-select-profile.svg
Labels: 컴포넌트, 스타일

#226 체크박스 default, disabled svg 변경 & hover 이벤트 추가
  src/app/_components/checkbox/Checkbox.tsx
  src/app/globals.css
  src/assets/icons/checkbox/default-checkbox.svg
  src/assets/icons/checkbox/disabled-checkbox.svg
Labels: 컴포넌트, 스타일

#228 버튼 hover, pressed 스타일 적용
  src/app/(beforeLogin)/_components/SocialLoginButton.tsx
  src/app/_components/common/button/BottomSheetButton.tsx
  tailwind.config.ts
Labels: 컴포넌트, 스타일

#229 사진 바꾸기 hover, pressed 스타일 추가
  src/app/_components/common/button/PictureChangeButton.tsx
Labels: 컴포넌트, 스타일

#233 알림, 헤더, arrow : hover,pressed / 클릭 영역 조정
  src/app/_components/common/header/BasicHeader.tsx
  src/app/_components/common/header/ControlHeader.tsx
  src/app/_components/common/header/NotificationHeader.tsx
  src/app/_components/icon/arrow/LeftArrowIcon.tsx
  src/app/_components/icon/arrow/RightArrowIcon.tsx
  src/assets/icons/arrow/leftArrow.svg
  src/assets/icons/arrow/rightArrow.svg
Labels: 컴포넌트, 스타일

#235 수정/삭제, 모달, 사진 추가 버튼 hover,pressed / 케밥 아이콘 : 클릭 영역 조정
  src/app/(afterLogin)/(main)/home/daily/_components/DailyThread.tsx
  src/app/(afterLogin)/posts/_components/WritePostMain.tsx
  src/app/(afterLogin)/posts/_components/imageUpload/ImageUpload.tsx
  src/app/_components/common/button/EditDeleteButton.tsx
  src/app/_components/common/button/PopUpButton.stories.tsx
  src/app/_components/common/button/PopUpButton.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/modal/Modal.tsx
  src/app/_components/icon/kebabMenu/KebabMenuIcon.tsx
Labels: 컴포넌트, 스타일

#231 마음함 API 연결
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.stories.tsx
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.tsx
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePostView.tsx
  src/app/(afterLogin)/(main)/home/calendar/_components/Calendar.tsx
  src/app/(afterLogin)/(main)/home/daily/_components/DailyView.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/icon/like/LikeIcon.tsx
  src/app/_store/favoritePostsStore.ts
  src/app/_store/likeStore.ts
  src/app/_store/localstorage/LocalStorage.tsx
  src/app/_store/topicStore.ts
  src/type/index.ts
Labels: 기능

#240 채팅 전송 버튼 : pressed 및 enter key 적용
  src/app/_components/input/InputChat.tsx
  src/app/globals.css
Labels: 컴포넌트, 스타일

#242 홈, 데일리 UpperTabBar : hover, pressed
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/upperTabBar/TabButton.tsx
  src/app/_components/icon/kebabMenu/KebabMenuIcon.tsx
Labels: 컴포넌트, 스타일

#243 리액션 칩, 추가 버튼 스타일 수정 및 hover,pressed
  src/app/(afterLogin)/posts/[postId]/_components/reaction/chip/AddReactionChip.tsx
  src/app/(afterLogin)/posts/[postId]/_components/reaction/chip/ReactionChip.tsx
  tailwind.config.ts
Labels: 컴포넌트, 스타일

#247 사진 삭제 X 버튼(게시글 작성) : hover, pressed
  src/app/(afterLogin)/posts/_components/imageUpload/ImageUpload.tsx
  src/app/_components/icon/delete/ImageDeleteIcon.tsx
  src/app/globals.css
  src/assets/icons/delete/imageDelete.svg
Labels: 컴포넌트, 스타일

#245 토스트 팝업 디자인 변경
  src/app/_components/common/popup/ToastPopUp.tsx
  src/assets/icons/info/info.svg
Labels: 컴포넌트, 스타일

#248 이미지 보기 페이지 X 버튼 : hover, pressed
  src/app/(afterLogin)/posts/[postId]/image-modal/_components/ImageModalMain.tsx
  src/app/globals.css
Labels: 컴포넌트, 스타일

#250 BottomMenuBar hover,pressed
  src/app/_components/common/bottomMenuBar/BottomMenuBar.tsx
  src/app/globals.css
Labels: 컴포넌트, 스타일

#252 게시글 작성 버튼 hover, pressed
  src/app/(afterLogin)/(main)/home/daily/_components/PostButton.tsx
  tailwind.config.ts
Labels: 컴포넌트, 스타일

#253 서비스 기능 소개 페이지 추가
  src/app/(afterLogin)/(main)/mypage/_components/service/ServiceInfo.tsx
  src/app/(afterLogin)/introduce/_components/IntroduceDescription.tsx
  src/app/(afterLogin)/introduce/_components/IntroduceSubTitle.tsx
  src/app/(afterLogin)/introduce/_components/IntroduceTitle.tsx
  src/app/(afterLogin)/introduce/page.tsx
  src/app/_components/common/bottomSheet/FamilySelectButton.tsx
  src/assets/icons/profile/family-select-profile.svg
  src/assets/images/introduce/introduce_calendar.png
  src/assets/images/introduce/introduce_daily.png
  src/assets/images/introduce/introduce_favorite.png
  src/assets/images/introduce/introduce_member.png
  tailwind.config.ts
Labels: 페이지, 스타일

#258 하트 아이콘 애니메이션 적용
  .gitignore
  src/app/_components/icon/like/LikeIcon.tsx
  src/assets/icons/like/activeLike.svg
  src/assets/icons/like/like.svg
Labels: 스타일, 기능

#263 마음함 hover, pressed 스타일 적용
  src/app/(afterLogin)/(main)/favorites/_components/FavoritePost.tsx
Labels: 스타일

#264 마이페이지 모듈, 프로필 수정 버튼 hover, pressed
  src/app/(afterLogin)/(main)/mypage/_components/MyPageMain.tsx
  src/app/(afterLogin)/(main)/mypage/_components/MyTitle.tsx
  src/app/(afterLogin)/(main)/mypage/_components/account/AccountSetting.tsx
  src/app/(afterLogin)/(main)/mypage/_components/addHome/AddHome.tsx
  src/app/(afterLogin)/(main)/mypage/_components/family/FamilyItem.tsx
  src/app/(afterLogin)/(main)/mypage/_components/notification/NotificationItem.tsx
  src/app/(afterLogin)/(main)/mypage/_components/notification/NotificationSetting.tsx
  src/app/(afterLogin)/(main)/mypage/_components/service/ServiceInfo.tsx
  src/app/(afterLogin)/(main)/mypage/_components/switch/ToggleSwitch.stories.tsx
  src/app/(afterLogin)/(main)/mypage/_components/switch/ToggleSwitch.tsx
  src/app/globals.css
Labels: 컴포넌트, 스타일

#266 링크 초대 hover, pressed
  src/app/(afterLogin)/(main)/members/_components/MemberAdd.tsx
Labels: 컴포넌트, 스타일

#268 캘린더 Day 컴포넌트 : hover, pressed
  src/app/(afterLogin)/(main)/home/calendar/_components/Day.tsx
  src/app/_components/common/dateController/DateController.tsx
  tailwind.config.ts
Labels: fix, 스타일

#269 reaction hover, pressed 스타일 적용
  src/app/(afterLogin)/posts/[postId]/_components/reaction/ReactionMenu.tsx
Labels: 스타일

#270 모달 팝업 애니메이션 적용
  src/app/(afterLogin)/(main)/members/_components/MemberProfile.tsx
  src/app/(afterLogin)/(main)/mypage/@modal/(.)account-deletion/_components/AccountDeletionContent.tsx
  src/app/(afterLogin)/(main)/mypage/account-deletion/_components/AccountDeletionContent.tsx
  src/app/(afterLogin)/(profile)/family-edit/_components/FamilyDelete.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/modal/Modal.tsx
  src/app/_components/common/popup/PopUp.stories.tsx
Labels: 스타일, 기능

#272 모달 취소시 ModalBackground fade-out 애니메이션 적용
  src/app/(afterLogin)/(main)/members/_components/MemberProfile.tsx
  src/app/(afterLogin)/(main)/mypage/@modal/(.)account-deletion/_components/AccountDeletionContent.tsx
  src/app/(afterLogin)/(main)/mypage/account-deletion/_components/AccountDeletionContent.tsx
  src/app/(afterLogin)/(profile)/family-edit/_components/FamilyDelete.tsx
  src/app/_components/common/daily/DailyUserTitle.tsx
  src/app/_components/common/modal/Modal.tsx
  src/app/_hooks/useModal.ts
  src/app/_store/modalStore.ts
Labels: fix, 스타일

#274 알림함 api 연결 및 디자인 수정 사항 적용
  src/app/(afterLogin)/notification/_components/notification/Notification.tsx
  src/app/(afterLogin)/notification/_components/notification/NotificationBox.stories.tsx
  src/app/(afterLogin)/notification/_components/notification/NotificationBox.tsx
  src/app/(afterLogin)/notification/_components/notification/NotificationList.tsx
  src/app/_api/apiRoutes.ts
  src/app/_components/common/header/NotificationHeader.tsx
  src/app/_components/icon/Icons.stories.tsx
  src/app/_components/icon/notification/NoticeIcon.tsx
  src/type/index.ts
Labels: 스타일, 기능

#276 Meta 데이터 페이지마다 적용
  src/app/(afterLogin)/(main)/favorites/page.tsx
  src/app/(afterLogin)/(main)/home/calendar/page.tsx
  src/app/(afterLogin)/(main)/home/daily/page.tsx
  src/app/(afterLogin)/(main)/members/page.tsx
  src/app/(afterLogin)/(main)/mypage/layout.tsx
  src/app/(afterLogin)/(profile)/family-edit/layout.tsx
  src/app/(afterLogin)/(profile)/family/page.tsx
  src/app/(afterLogin)/family-select/page.tsx
  src/app/(afterLogin)/introduce/page.tsx
  src/app/(afterLogin)/notification/page.tsx
  src/app/(afterLogin)/posts/[postId]/page.tsx
  src/app/(afterLogin)/posts/page.tsx
  src/app/(beforeLogin)/layout.tsx
Labels: 기능

#278 401 상황 발생시 쿠키 제거 및 홈화면 으로 이동하도록 설정
  src/app/_api/api.ts
Labels: fix

#279 feat : 사진 추가
  public/opengraph-image.png
Labels: fix

#282 401 리턴 시 제대로 쿠키가 삭제되지 않아 수정
  src/app/_api/api.ts
Labels: fix

#283 README 문서작성
  README.md
Labels: documentation
